#
# Makefile for nfc devices
#

obj-$(CONFIG_PN65T_NFC)		+= pn544.o
#obj-$(CONFIG_NFC_PN533)	+= pn533.o
#obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o
#obj-$(CONFIG_NFC_QNCI)		+= pn544.o
#obj-$(CONFIG_PN65T_NFC_SPI)	+= spi_driver/

ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
